### ISSUE TITLE
Use on gitlab

### ISSUE THREAD

**Issue by grero** [brauner/psychodoc#1]
Hey!
 I realise this is a long shot, but I came across this while searching for a way to do CI on gitlab for a project that uses PsychoPy. Did you ever use this in that context? Just for reference, this is the .gitlab-ci.yml file

```yml
image: brauner/psychodoc

variables:
  CONDA: "true"
  PYTHON_VERSION: "2.7"
  WXPYTHON: "3"
  OPENPYXL: "2.4"
  DISPLAY: ":99.0"
  AUDIODEV: "null"

before_script:
  - sudo apt-get install pip
  - pip install coverage

default:
  script:
    - coverage run -m py.test -s -q
```

and these are the last few lines of the job output, seemingly telling me that I am not able to use sudo

```bash
$ sudo apt-get install pip

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified
ERROR: Job failed: exit code 1
```

Of course, feel free to close this if nothing immediate comes to mind : ) . Thanks anyway for making this available.

**Comment by brauner** [comment]
Hm, @stgraber, is there a way to force pseudo-tty allocation? Any tricks we do for Jenkins?

**Comment by stgraber** [comment]
@brauner we run it through `script`

**Comment by brauner** [comment]
Oh right, I even wrote that code. :D Ups.

**Comment by grero** [comment]
Thanks for getting back to me on this. I just wanted to let you know that I did find a solution for my need, which I'll post here for reference. This is the .gitlab-ci.yml file that allowed me to test my code

```yml
image: neurodebian:stretch

variables:
  CONDA: "true"
  PYTHON_VERSION: "2.7"
  WXPYTHON: "3"
  OPENPYXL: "2.4"
  DISPLAY: :99.0
  AUDIODEV: "null"

before_script:
  - apt-get update -qq
  - DEBIAN_FRONTEND=noninteractive apt-get install neurodebian-popularity-contest -y -q
  - apt-get install -qq wget
  - wget -O- http://neuro.debian.net/lists/stretch.us-nh.full | tee /etc/apt/sources.list.d/neurodebian.sources.list
  - wget -q -O- http://neuro.debian.net/_static/neuro.debian.net.asc |  apt-key add -
  - apt-get update -qq
  - apt-get install -qq psychopy
  - apt-get install -qq python-pip
  - apt-get install -qq xvfb xauth libgl1-mesa-dri ffmpeg
  - pip install xvfbwrapper
  - pip install json-tricks
  - pip install coverage

default:
  script:
    - /usr/bin/xvfb-run -s "-screen 0 1024x768x24"  coverage run -m py.test -s -q
    - coverage report
```
